version: "3.8"

services:
  flask:
    build: ./app
    container_name: flask_service
    restart: unless-stopped
    env_file:
      - ./app/.env

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "8182:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
